export const CHALLENGE_BANK = [
  'No Screen Time During Meals',
  'Drink a Glass of Water Before Breakfast',
  'Stretch for 5 Minutes After Waking Up',
  'Walk 1,000 Steps After Dinner',
  'Read 10 Pages of a Book',
  'No Caffeine After 2 PM',
  'Write Down 3 Things You Are Grateful For',
  'Take a 10-minute Brisk Walk',
  'Eat a Serving of Green Vegetables',
  'Do 15 Push-ups',
  'Do 20 Squats',
  'Hold a Plank for 30 Seconds',
  'Take the Stairs Instead of the Elevator',
  'Meditate for 5 Minutes',
  'Practice Deep Breathing for 2 Minutes',
  'Drink 2 Liters of Water Today',
  'Floss Your Teeth',
  'Get 8 Hours of Sleep',
  'Avoid Added Sugars for 24 Hours',
  'Eat a Piece of Fresh Fruit',
  'Do 10 Minutes of Yoga',
  'Stand Up and Walk Around Every Hour',
  'Keep a Food Journal for Today',
  'Cook a Healthy Meal at Home',
  'Avoid Fried Foods Today',
  'Limit Sodium Intake Today',
  'Eat a Handful of Unsalted Nuts',
  'Do a 5-Minute Core Workout',
  'Walk 5,000 Steps Today',
  'Do 10 Lunges on Each Leg',
  'Stretch Your Neck and Shoulders',
  'Spend 15 Minutes in the Sun',
  'Avoid Alcohol Today',
  'Chew Your Food Slowly',
  'Take a Cold Shower',
  'Limit Social Media to 30 Minutes',
  'Call a Friend or Family Member',
  'Write Down Your Daily Goals',
  'Declutter Your Workspace',
  'Do Not Eat 2 Hours Before Bed',
  'Drink Herbal Tea Before Bed',
  'Avoid Fast Food Today',
  'Eat a Source of Lean Protein',
  'Eat a Source of Omega-3',
  'Take a Multivitamin',
  'Do a 15-Minute HIIT Workout',
  'Walk 10,000 Steps Today',
  'Do 30 Jumping Jacks',
  'Stretch Your Hamstrings',
  'Try a New Healthy Recipe',
  'Avoid Processed Meats',
  'Eat Whole Grains Instead of Refined',
  'Do a Posture Check Every Hour',
  'Spend 10 Minutes in Nature',
  'Listen to a Calming Podcast or Music',
  'Practice Mindful Eating',
  'Limit Screen Time Before Bed',
  'Read a Health-Related Article',
  'Do 10 Burpees',
  'Hold a Wall Sit for 45 Seconds',
  'Do 20 Calf Raises',
  'Stretch Your Lower Back',
  'Eat 3 Servings of Vegetables',
  'Avoid Sugary Drinks Today',
  'Drink a Glass of Lemon Water',
  'Take a Probiotic',
  'Eat a Source of Fiber',
  'Do a 20-Minute Cardio Session',
  'Walk for 30 Minutes',
  'Do 15 Tricep Dips',
  'Stretch Your Quads',
  'Prepare Healthy Snacks for the Week',
  'Avoid Artificial Sweeteners',
  'Eat a Rainbow of Colors Today',
  'Take a 5-Minute Break from Work',
  'Practice Gratitude Before Bed',
  'Do 50 High Knees',
  'Hold a Plank for 60 Seconds',
  'Do 20 Bicycle Crunches',
  'Stretch Your Chest and Arms',
  'Eat a Healthy Breakfast',
  'Avoid Snacking After Dinner',
  'Drink Green Tea',
  'Take a Vitamin D Supplement',
  'Eat a Source of Calcium',
  'Do a 30-Minute Strength Workout',
  'Walk for 45 Minutes',
  'Do 20 Glute Bridges',
  'Stretch Your Calves',
  'Plan Your Meals for Tomorrow',
  'Avoid Trans Fats',
  'Eat a Source of Iron',
  'Take 10 Deep Breaths',
  'Compliment Someone Today',
  'Do 100 Jumping Jacks Throughout the Day',
  'Hold a Plank for 90 Seconds',
  'Do 30 Sit-ups',
  'Stretch Your Hips',
  'Eat a Healthy Lunch',
  'Avoid White Bread and Pasta'
];
